mode: auto

colors:
  primary: "#6200ee"
  # bg: "#F5F5F5"
  selection_bg: "#8e71c1" # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

avatar:
  url: https://q1.qlogo.cn/g?b=qq&nk=79099400&s=640
  opacity: 1
  mickey_mouse: true
  status:
    enable: true
    emoji: ğŸ˜Š
    message: æ°¸è¿œç›¸ä¿¡ç¾å¥½çš„äº‹æƒ…å³å°†å‘ç”Ÿ.
sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: true
    amount: 20

reward:
  enable: true
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: https://s4.ax1x.com/2022/02/09/HJAFuq.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: https://s4.ax1x.com/2022/02/09/HJACgs.png
      color: "#12B7F5"
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://s4.ax1x.com/2022/02/09/HJAPvn.png
      icon: icon-wechat-pay-line
banner:
  enable: true
  title:  æ€ç±³ç±³
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

notice:
  enable: false
  content: Welcome Home.

head:
  css:
   # fonts: https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap
   js:
    base:
    async:
    defer:

bg_image:
  enable: false
  # url: https://bing.biturl.top/?resolution=1920&format=image&index=0&mkt=zh-CN
  # dark:
  # blur: 2px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

trianglify:
  enable: true
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues","YlOrRd"]'
  opacity: 0.5

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/hqw567/hqw567.github.io/discussions/" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: true
  serverURL: https://waline.simimi.cn
  visitor: true
  comment: true
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: ["nick"]

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: yunyoujun
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

footer:
  since: 2022
  icon:
    name: icon-github-line
    url: https://github.com/hqw567
    animated: true
    color: "#0078E7"
    title: æ€ç±³ç±³çš„GitHub
  beian:
    enable: true
    icp: æ¹˜ICPå¤‡2022002172å·
  support:
    enable: false
    title: åˆæ‹äº‘
    link: https://www.upyun.com
    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿ
  powered:
    enable: false
  live_time:
    enable: true
    prefix: æœ¬åšå®¢éƒ¨åˆ†èµ„æºæ¥è‡ªäº’è”ç½‘ï¼Œå¦‚æœ‰ä¾µæƒï¼Œè¯·è”ç³»åˆ é™¤<br>æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-01-01T00:00:00"
  custom_text:

wordcloud:
  enable: false
  height: 350

mourn:
  enable: true
  days:
    - "4-4"
  # - "2-3"
engine_search:
  enable: true
  href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: www.simimi.cn

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
#algolia_search:
#  enable: true
  # ...
codeblock:
  copy_btn: true
  light:
  dark:

google_analytics:
  enable: true
  id: G-4KNE7DCHW1

google_adsense:
  enable: true
  client: ca-pub-8809383571319105

post_edit:
  enable: true
  url: https://github.com/hqw567/hqw567.github.io/tree/hexo/source/

albums:
  enable: false

girls:
  enable: false

tags:
  Vue: "#4fc08d"
  Hexo: "#0E834D"
  CSS: "#5298d1"
  Node.js: "#026E00"
  Git: "#F14E32"
  React: "#61dafb"
  Python: "#3776ab"
  PHP: "#8892BF"
  VS Code: "#0066B8"
  JavaScript: "#F4DF4F"
  TypeScript: "#317AC6"
  Laravel: "#F4645F"

categories:
  æ€ç±³ç±³çš„å°ç¬”è®°: "#FB7299"

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links
    icon: icon-genderless-line
    color: dodgerblue

menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: icon-clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: false
  id: GTM-M9KWR9L

wordcount:
  enable: true
  count: true
  time: true

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

lazyload:
  enable: true
  
social:
  #- name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
   # link: /atom.xml # config.feed.path
   # icon: icon-rss-line
    #color: orange
  - name: QQ 
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: https://wpa.qq.com/msgrd?v=3&uin=79099400&site=qq&menu=yes
    icon: icon-qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/hqw567
    icon: icon-github-line
    color: "#6e5494"
  # - name: å¾®åš
  #   link: https://weibo.com/jizhideyunyoujun
  #   icon: icon-weibo-line
  #   color: "#E6162D"
  # - name: è±†ç“£
  #   link: https://www.douban.com/people/yunyoujun/
  #   icon: icon-douban-line
  #   color: "#007722"
  # - name: ç½‘æ˜“äº‘éŸ³ä¹
  #   link: https://music.163.com/#/user/home?id=247102977
  #   icon: icon-netease-cloud-music-line
  #   color: "#C20C0C"
  # - name: çŸ¥ä¹
  #   link: https://www.zhihu.com/people/yunyoujun/
  #   icon: icon-zhihu-line
  #   color: "#0084FF"
  # - name: å“”å“©å“”å“©
  #   link: https://space.bilibili.com/1579790
  #   icon: icon-bilibili-line
  #   color: "#FF8EB3"
  # - name: å¾®ä¿¡å…¬ä¼—å·
  #   link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
  #   icon: icon-wechat-2-line
  #   color: "#1AAD19"
  # - name: Twitter
  #   link: https://twitter.com/YunYouJun
  #   icon: icon-twitter-line
  #   color: "#1da1f2"
  # - name: Telegram
  #   link: https://t.me/yunyoujun_group
  #   icon: icon-telegram-line
  #   color: "#0088CC"
  - name: Telegram Channel
    link: https://t.me/elpsycn
    # icon: icon-telegram-fill
    icon: icon-telegram-line
    color: "#0088CC"
  - name: E-Mail
    link: mailto:hqw6@qq.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: Travelling
    link: https://travellings.link
    icon: icon-train-line
    color: black

aplayer:
  global: false
  meting: true
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: false
    autoplay: true
    theme: "#2980b9"
    fixed: true
    mimi: false
    loop: all
    order: list
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: false
    listMaxHeight: 340px
    audio:
      - name: æ˜Ÿå®¿è®¡æ—¶
        artist: æ‰ç”°æœ—/æ´›å¤©ä¾
        url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/audio/star-timer.mp3
        cover: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0.jpg
    meting:
      enable: true
      id: 308168565
      server: netease
      type: playlist

pjax:
  enable: false