mode: auto

colors:
  #primary: "#6200ee"
  # bg: "#F5F5F5"
  selection_bg: '#8e71c1' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

avatar:
  url: https://q1.qlogo.cn/g?b=qq&nk=79099400&s=640
  opacity: 1
  mickey_mouse: true
  status:
    enable: true
    emoji: ğŸ˜Š
    message: å±±æœ‰æœ¨å…®æœ¨æœ‰æï¼Œå¿ƒæ‚¦å›å…®å›ä¸çŸ¥ã€‚
sidebar:
  bg_image: /images/sidebar/sidebar.png
  bg_position: bottom 3rem center
  tagcloud:
    enable: true
    amount: 20

reward:
  enable: true
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: /images/pay/zfb.jpg
      color: '#226bf3'
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: /images/pay/qq.png
      color: '#05b0ff'
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: /images/pay/wx.png
      color: '#07c160'
      icon: icon-wechat-pay-line
banner:
  enable: true
  title: æ€ç±³ç±³
  border: true
  cloud:
    enable: true
    color: 'white'
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

notice:
  enable: false
  content: Welcome Home.

favicon: /favicon.ico

bg_image:
  enable: false
  # url: https://bing.biturl.top/?resolution=1920&format=image&index=0&mkt=zh-CN
  # dark:
  # blur: 2px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

trianglify:
  enable: true
  cellSize: 15
  width: 1000
  height: 800
  # palette: '["YlGnBu", "GnBu", "Purples", "Blues","YlOrRd"]'
  opacity: 0.5
  colorFunction: trianglify.colorFunctions.shadows()

fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/hqw567/hqw567.github.io/discussions/" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: true
  serverURL: https://waline.simimi.cn
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: ['nick']

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

footer:
  since: 2022
  icon:
    name: icon-github-line
    url: https://github.com/hqw567
    animated: true
    color: '#0078E7'
    title: æ€ç±³ç±³çš„GitHub
  beian:
    enable: true
    icp: æ¹˜ICPå¤‡2022002172å·
  support:
    enable: true
    title: åˆæ‹äº‘
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://fastly.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿ
  powered:
    enable: false
  live_time:
    enable: true
    prefix: æœ¬åšå®¢éƒ¨åˆ†èµ„æºæ¥è‡ªäº’è”ç½‘ï¼Œå¦‚æœ‰ä¾µæƒï¼Œè¯·è”ç³»åˆ é™¤<br>æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2022-01-01T00:00:00'
  custom_text:

wordcloud:
  enable: false
  height: 350

mourn:
  enable: true
  days:
    # - '4-4'

engine_search:
  enable: false
  # href: 'https://www.bing.com/search?q=site:'
  # href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  domain: simimi.cn

algolia_search:
  enable: true
  hits:
    per_page: 10 # the number of search results per page
# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
#algolia_search:
#  enable: true
# ...
codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow
google_analytics:
  enable: true
  id: G-4KNE7DCHW1

google_adsense:
  enable: true
  client: ca-pub-8809383571319105

post_edit:
  enable: true
  url: https://github.com/hqw567/hqw567.github.io/tree/hexo/source/

albums:
  enable: false

tags:
  Vue: '#4fc08d'
  Hexo: '#0E834D'
  CSS: '#5298d1'
  Node.js: '#026E00'
  Git: '#F14E32'
  React: '#61dafb'
  Python: '#3776ab'
  PHP: '#8892BF'
  VS Code: '#0066B8'
  JavaScript: '#F4DF4F'
  TypeScript: '#317AC6'
  Laravel: '#F4645F'
  å‰ç«¯: '#e300a8'

categories:
  æ€ç±³ç±³çš„å°ç¬”è®°: '#FB7299'

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links
    icon: icon-genderless-line
    color: dodgerblue

menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: icon-clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: false
  id: GTM-M9KWR9L

wordcount:
  enable: true
  count: true
  time: true

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

lazyload:
  enable: true

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: QQ
    link: https://wpa.qq.com/msgrd?v=3&uin=79099400&site=qq&menu=yes
    icon: icon-qq-line
    color: '#12B7F5'
  - name: GitHub
    link: https://github.com/hqw567
    icon: icon-github-line
    color: '#6e5494'
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=616215227
    icon: icon-netease-cloud-music-line
    color: '#C20C0C'
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/hqw567/
    icon: icon-zhihu-line
    color: '#0084FF'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/477836218
    icon: icon-bilibili-line
    color: '#FF8EB3'
  - name: E-Mail
    link: mailto:hqw6@qq.com
    icon: icon-mail-line
    color: '#4c000a'
  - name: Travelling
    link: https://travellings.link
    icon: icon-train-line
    color: black

pjax:
  enable: false

busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: icon-user-line
  site_pv: true
  site_pv_icon: icon-eye-line
  page_pv: false
  page_pv_icon: icon-eye-line
